### PR TITLE
2016 04 15 base styling

### PR DESCRIPTION
**Pull request by charlieartist**
OK-First round here, with base splash page. Due to issues with base URL, the banner image, and even body field images aren't displaying properly. In addition, not sure if this is because of COD, but I couldn't add a location field to build the map functionality.

### CODE REVIEW

**Comment by jdearie** [comment]
My personal preference - lose the map on the home page. It was nice to help fill space when we first launched, but I find myself getting caught in a zooming map when I try to scroll the page... so I would prefer we go ahead and drop it.

**Comment by charlieartist** [comment]
The map will be off the homepage, on the full site. For now, this is to replicate the splash page until the rest of the functionality is built out. Even the navigation only links to anchors on this page, for the moment.

Ideally, there will be a page dedicated to Location/Venue, similar to this: http://www.uxpa2016.org/stay

I agree with you on the scrolling, and why it's limited to the page width on the example above.

**Comment by timwood** [comment]
@charlieartist Not sure whether you are using Leaflet, but there is a great, simple plugin called Leaflet.Sleep which helps to prevent the scrolling / zoom issue.

http://cliffcloud.github.io/Leaflet.Sleep/

**Comment by charlieartist** [comment]
@timwood Thanks--I'll check it out. As a matter of fact, I am using Leaflet, and on the full site, the map will be moved off the homepage to a dedicated Location page.

**Comment by sarahjean** [comment]
@timwood nice find!

**Comment by timwood** [comment]
@sarahjean Thanks!

**Comment by timwood** [comment]
I was going to make it a module on D.O, but haven't gotten to finish that yet.

**Comment by sarahjean** [comment]
@charlieartist The theme has been commited on PR #46 with all the build stuff, I think we can close this one and do a few PRs with cleanup. I have the feature modules and a few fixes in the PR for #47 for some CSS stuff, didn't see the issues with body images, but you can set your base URL in local.settings.php, or take out whatever is in there if need be.

**Pull request closed without merging**
